/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.event.*;
import java.awt.Color;
/**
 *
 * @author Feyesel Sultan
 */
public class forgotForm extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet Rs=null;
    int mouseX, mouseY;
    
    public forgotForm() {
        initComponents();
        con = MyConnection.getConnection();
        mainPanel.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        l_question = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(51, 255, 204));
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerPanelMouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerPanelMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recovery Page !");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/Exit1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("USERNAME :");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 185, -1, 20));

        txtCombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCombo.setForeground(new java.awt.Color(102, 102, 102));
        txtCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        txtCombo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        mainPanel.add(txtCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 290, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("DESIGNATION :");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtUname.setForeground(new java.awt.Color(102, 102, 102));
        txtUname.setText("After Filling username Press Enter Key");
        txtUname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        txtUname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnameFocusLost(evt);
            }
        });
        txtUname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnameKeyPressed(evt);
            }
        });
        mainPanel.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 290, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("FULL NAME :");
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 20));

        txtFname.setEditable(false);
        txtFname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        mainPanel.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 290, 30));

        l_question.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_question.setForeground(new java.awt.Color(51, 51, 51));
        l_question.setText("SECURITY QUESTION :");
        mainPanel.add(l_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 20));

        txtAnswer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        mainPanel.add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 290, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("PASSWORD :");
        mainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, 20));

        txtPass.setEditable(false);
        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        mainPanel.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 290, 30));

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RECOVER");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 300, 40));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCEL");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 150, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void headerPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseDragged
        //mouse drage
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX,y - mouseY);
    }//GEN-LAST:event_headerPanelMouseDragged

    private void headerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMousePressed
        // mouse press header panel
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_headerPanelMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // LOGIN
        loginForm login = new loginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // RECOVER btn
        //recover button clicked
        String answer = txtAnswer.getText();
        String role=(String)txtCombo.getSelectedItem();
        if(answer.equals("")){
            JOptionPane.showMessageDialog(null, "PLAEASE ANSWER THE SECURITY QUESTION TO RETRIVE YOUR PASSWORD !","INFORMATIVE MESSAGE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(role.equals("User")){
                try {
                    String sql = "SELECT * FROM `user` WHERE `answer`='"+answer+"'";
                    pst = con.prepareStatement(sql);
                    Rs = pst.executeQuery(); 
                    if(Rs.next()){
                        String pass = Rs.getString(3);
                        txtPass.setText("YOUR PASSWORD IS: "+pass);
                    }else{
                        JOptionPane.showMessageDialog(null, "INCORRECT ANSWER FOR THE GIVEN QUESTION!!!!");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }else{
                try {
                    String sql = "SELECT * FROM `admin` WHERE `answer`='"+answer+"'";
                    pst = con.prepareStatement(sql);
                    Rs = pst.executeQuery(); 
                    if(Rs.next()){
                        String pass = Rs.getString(3);
                        txtPass.setText("YOUR PASSWORD IS: "+pass);
                    }else{
                        JOptionPane.showMessageDialog(null, "INCORRECT ANSWER FOR THE GIVEN QUESTION!!!!");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }//FOOD SELECTED CHECK
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnameKeyPressed
        // enter press
        // fill username and press Enter key
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String role=(String)txtCombo.getSelectedItem();
            if(role.equals("User")){
                try {
                    String sql = "SELECT * FROM `user` WHERE `uname` = ?";
                    pst = con.prepareStatement(sql);
                    pst.setString(1, txtUname.getText());
                    Rs = pst.executeQuery();

                    if(Rs.next()){
                        txtFname.setText(Rs.getString(4)+" "+Rs.getString(5));
                        l_question.setText(Rs.getString(6));
                    }else{
                        JOptionPane.showMessageDialog(null, "NO RECORD MATCHES USERNAME !!!");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }else{
                try {
                    String sql = "SELECT * FROM `admin` WHERE `uname` = ?";
                    pst = con.prepareStatement(sql);
                    pst.setString(1, txtUname.getText());
                    Rs = pst.executeQuery();

                    if(Rs.next()){
                        txtFname.setText(Rs.getString(4)+" "+Rs.getString(5));
                        l_question.setText(Rs.getString(6));
                    }else{
                        JOptionPane.showMessageDialog(null, "NO RECORD MATCHES USERNAME !!!");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_txtUnameKeyPressed

    private void txtUnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnameFocusGained
        // Username field foucus
        if(txtUname.getText().trim().equals("After Filling username Press Enter Key")){
            txtUname.setText("");
        }
        txtUname.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtUnameFocusGained

    private void txtUnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnameFocusLost
        /// Username field foucus lost
        if(txtUname.getText().trim().equals("")){
            txtUname.setText("After Filling username Press Enter Key");
            txtFname.setText("");
            txtAnswer.setText("");
            txtPass.setText("");
        }
        txtUname.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_txtUnameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel l_question;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JComboBox<String> txtCombo;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
